baseURL: "https://nrclaud.io"
languageCode: en-us
title: nrclaud.io
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
        enabled: true
        title: "nrclaud.io" # optional default will be site title
        subtitle: "Uncovering the hidden beauty of biological data and the natural world through computer science and photography, in no particular order"
        buttons:
          - name: Twitter
            url: "https://twitter.com/nr_claudio"
          - name: Github
            url: "https://github.com/nrclaudio"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:c.novella.rausell@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/nrclaudio"
    - name: "github"
      url: "https://github.com/nrclaudio"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
